#version 430 core

layout (local_size_x = 10, local_size_y = 10, local_size_z = 10) in;


layout(rgba16f, binding = 0) uniform image3D imgOutput;

layout(std430, binding = 1) buffer Vertices {
	vec3 vertices[];
};

//layout(std430, binding = 2) buffer Indices {
//	uint indices[];
//};

float sdfSphere(vec3 p, vec3 center, float radius) {
	return length(p - center) - radius;
}

// https://iquilezles.org/articles/triangledistance/
float dot2( in vec3 v ) { return dot(v,v); }

float udTriangle( in vec3 v1, in vec3 v2, in vec3 v3, in vec3 p )
{
	// prepare data
	vec3 v21 = v2 - v1; vec3 p1 = p - v1;
	vec3 v32 = v3 - v2; vec3 p2 = p - v2;
	vec3 v13 = v1 - v3; vec3 p3 = p - v3;
	vec3 nor = cross( v21, v13 );

	return sqrt( // inside/outside test
	(sign(dot(cross(v21,nor),p1)) +
	sign(dot(cross(v32,nor),p2)) +
	sign(dot(cross(v13,nor),p3))<2.0)
	?
	// 3 edges
	min( min(
	dot2(v21*clamp(dot(v21,p1)/dot2(v21),0.0,1.0)-p1),
	dot2(v32*clamp(dot(v32,p2)/dot2(v32),0.0,1.0)-p2) ),
	dot2(v13*clamp(dot(v13,p3)/dot2(v13),0.0,1.0)-p3) )
	:
	// 1 face
	dot(nor,p1)*dot(nor,p1)/dot2(nor) );
}

void main() {
	ivec3 pixelCoords = ivec3(gl_GlobalInvocationID);
	vec3 uv = vec3(pixelCoords) / vec3(imageSize(imgOutput));

	vec3 center = vec3(0.5);
	float radius = 0.25;
	float distance = sdfSphere(uv, center, radius);

	//imageStore(imgOutput, pixelCoords, vec4(vec3(distance), 1.0));

	float minDistance = 1000.0;
	int triangleCount = 967;
	for (int i = 0; i < triangleCount; i++) {
		vec3 v1 = vertices[i * 3 + 0];
		vec3 v2 = vertices[i * 3 + 1];
		vec3 v3 = vertices[i * 3 + 2];

		float dist = udTriangle(v1, v2, v3, uv);
		minDistance = min(minDistance, dist);
	}

	imageStore(imgOutput, pixelCoords, vec4(vec3(minDistance), 1.0));
}